/*! Generated by Aleph.js, do **NOT** change and ensure the file is **NOT** in the `.gitignore`. */

import { revive } from "aleph/server";
import { default as $0 } from "./routes/index.tsx";
import { default as $1, data as $$1 } from "./routes/todos.tsx";

revive("./routes/index.tsx", { default: $0 });
revive("./routes/todos.tsx", { default: $1, data: $$1 });